#!/usr/bin/env perl
use strict;
use warnings;
use File::Path qw(make_path);
use File::Basename;

if (@ARGV != 2) {
    die "Usage: $0 <markdown_file> <output_directory>\n";
}

my ($input_file, $output_dir) = @ARGV;

die "Input file '$input_file' does not exist\n" unless -f $input_file;

open my $fh, '<', $input_file or die "Cannot open '$input_file': $!\n";

my $content = do { local $/; <$fh> };
close $fh;

while ($content =~ /^(`{3,})\s*(?:(\w+)\s+)?(.+?)\s*\n(.*?)\n\1\s*$/gms) {
    my ($backticks, $language, $filepath, $file_content) = ($1, $2, $3, $4);
    
    next unless defined $filepath && $filepath ne '';
    
    my $output_path = "$output_dir/$filepath";
    
    my $dir = dirname($output_path);
    make_path($dir) unless -d $dir;
    
    open my $out_fh, '>', $output_path or die "Cannot create '$output_path': $!\n";
    print $out_fh $file_content;
    close $out_fh;
    
    print "Extracted: $filepath\n";
}